spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        platform: postgres
        url: jdbc:postgresql://localhost:5432/librarydb
        username: goksenin
        password: 1234
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        open-in-view: false
        generate-ddl: true

